-- DROP THE TABLE IF ALREADY EXISTS
DROP TABLE IF EXISTS ACTIVE_HABITS;

-- ACTIVE_HABITS is a table tracking active habits
CREATE TABLE ACTIVE_HABITS (
    HABIT_ID SMALLINT PRIMARY KEY UNIQUE,
    HABIT_NAME VARCHAR,
    PERIODICITY VARCHAR,
    LAST_INCREMENTATION_DATE DATE,
    STREAK_ACTIVE SMALLINT
    );


-- DROP THE TABLE IF ALREADY EXISTS
DROP TABLE IF EXISTS BROKEN_HABITS;

-- BROKEN_HABITS is a table holds broken habits
CREATE TABLE BROKEN_HABITS (
    HABIT_ID SMALLINT PRIMARY KEY UNIQUE,
    HABIT_NAME VARCHAR,
    PERIODICITY VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    STREAK_ENDED SMALLINT,
    FOREIGN KEY (HABIT_ID) REFERENCES ACTIVE_HABITS(HABIT_ID)
    );


-- DROP THE TABLE IF ALREADY EXISTS
DROP TABLE IF EXISTS TRACKING_HABITS;

-- TRACKING_HABITS is a table tracking creating, breaking, deleting, resetting, and incrementing habits
CREATE TABLE TRACKING_HABITS (
    OPERATION_ID SERIAL PRIMARY KEY,
    HABIT_ID SMALLINT,
    EVENT_NAME VARCHAR,
    EVENT_DATE DATETIME,
    FOREIGN KEY (HABIT_ID) REFERENCES ACTIVE_HABITS(HABIT_ID)
    );

